### PR TITLE
Add signal quality and strength

### PR DESCRIPTION
**Pull request by dioneimiodutzki**
Hi! I've added the signal strength and quality as separated sensors and updated the readme accordingly.

### CODE REVIEW

**Comment by uvjim** [comment]
Thanks. I'll try and have a look at this ASAP. I have another integration that needs some love and I'm quite time poor at the moment. Will see if I can make some time this weekend though.

You'll probably notice from other comments on the open issue re: this. I was toying with moving over to using devices as well. My thoughts are that there should be a "service" device that acts as the parent for the "tuner" devices. The entities relating to the tuners go with the tuner devices and things like updates, scanning, restart etc should go on the service device.

**Comment by dioneimiodutzki** [comment]
> Thanks. I'll try and have a look at this ASAP. I have another integration that needs some love and I'm quite time poor at the moment. Will see if I can make some time this weekend though.
> 
> You'll probably notice from other comments on the open issue re: this. I was toying with moving over to using devices as well. My thoughts are that there should be a "service" device that acts as the parent for the "tuner" devices. The entities relating to the tuners go with the tuner devices and things like updates, scanning, restart etc should go on the service device.

yep, i think a separated device for each tuner would make more sense - the way i added new entities here is really provisory.
I'm not very used to Python, but i'm gonna try to find some time to understand how to add more devices too.

**Comment by uvjim** [comment]
I didn't have time over the weekend sorry. I can handle the devices and additional entities as soon as I get back to this.

I already do it for one of my other integrations.

**Comment by uvjim** [comment]
Hi, I've re-worked a fair amount of the sensor code and split them into devices in the latest beta.  Let me know if that works, if it does we can close this PR and use what is currently in the main branch.

**Comment by dioneimiodutzki** [comment]
@uvjim just tested the beta and is working very well, thanks a lot! i'm closing the pr

**Pull request closed without merging**
